global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'jadwal-service'
    static_configs:
      - targets: ['jadwal-service:3002']

  - job_name: 'sensor-service'
    static_configs:
      - targets: ['sensor-service:3003']
